---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-get -y install lxd lxc-dev
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis
install:
  - sudo pip install molecule==2.0.0.0rc11
  - sudo pip install lxc-python2
script:
  - sudo su travis -c 'molecule create'
  - sudo su travis -c 'molecule converge'
  - udo su travis -c 'molecule verify'