---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-get -y install lxd lxc-dev
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis
install:
  - pip install molecule --pre
  - pip install lxc-python2
script:
  - molecule create
  - molecule converge
  - molecule verify