---
sudo: required
language: python
services:
  - docker
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-lxc/lxd-stable
  - sudo apt-get -qq update
  - sudo apt-get -y install lxd lxc-dev
  - sudo lxd init --auto;
  - sudo usermod -a -G lxd travis
  - sudo su travis -c 'lxc network create lxdbr0';
  - sudo su travis -c 'lxc network attach-profile lxdbr0 default eth0';
install:
  - sudo pip install molecule==2.0.0.0rc16
  - sudo pip install lxc-python2
script:
  - sudo su travis -c 'molecule create'
  - sudo su travis -c 'molecule converge'
  - sudo su travis -c 'molecule verify'