---
- name: start | ensure postfix is started and set to start on boot.
  systemd:
    state: started
    daemon_reload: "yes"
    enabled: true
    name: postfix

- name: start | make sure postfix is responding
  wait_for:
    port: 25
    delay: 3
    timeout: 90
