---
- name: Check cozystack_couchdb_cozy_password
  assert:
    that:
      - "cozystack_couchdb_cozy_password | trim != ''"
      - "cozystack_couchdb_cozy_password is defined"
    msg: "'cozystack_couchdb_cozy_password' must be define"

- name: Check cozystack_couchdb_cozy_password
  assert:
    that:
      - "cozystack_cozy_password | trim != ''"
      - "cozystack_cozy_password is not none"
      - "cozystack_cozy_password is defined"
    msg: "'cozystack_cozy_password' must be define"

- name: install | check if cozy-stack is already installed
  shell: "dpkg -l cozy-stack > /dev/null 2> /dev/null"
  changed_when: false
  register: cozy_stack_installed
  ignore_errors: true

- name: install | cosy-stack debconf
  debconf:
    name: cozy-stack
    question: "{{ item.question }}"
    value: "{{ item.value | quote }}"
    vtype: "{{ item.vtype }}"
  notify: reconfigure_cosy_stack
  no_log: true
  when: cozy_stack_installed|failed
  with_items:
    - { "question": "cozy-stack/couchdb/address", "vtype": "string", "value": "{{ cozystack_couchdb_address }}" }
    - { "question": "cozy-stack/couchdb/nodename", "vtype": "string", "value": "{{ cozystack_couchdb_nodename }}" }
    - { "question": "cozy-stack/couchdb/admin/user", "vtype": "string", "value": "{{ cozystack_couchdb_admin_user }}" }
    - { "question": "cozy-stack/couchdb/admin/password", "vtype": "password", "value": "{{ cozystack_couchdb_admin_password }}" }
    - { "question": "cozy-stack/couchdb/admin/password_again", "vtype": "password", "value": "{{ cozystack_couchdb_admin_password }}" }
    - { "question": "cozy-stack/couchdb/cozy/user", "vtype": "string", "value": "{{ cozystack_couchdb_cozy_user }}" }
    - { "question": "cozy-stack/couchdb/cozy/password", "vtype": "password", "value": "{{ cozystack_couchdb_cozy_password }}" }
    - { "question": "cozy-stack/couchdb/cozy/password_again", "vtype": "password", "value": "{{ cozystack_couchdb_cozy_password }}" }
    - { "question": "cozy-stack/cozy/password", "vtype": "password", "value": "{{ cozystack_cozy_password }}" }
    - { "question": "cozy-stack/cozy/password_again", "vtype": "password", "value": "{{ cozystack_cozy_password }}" }
    - { "question": "cozy-stack/address", "vtype": "string", "value": "{{ cozystack_address }}" }
    - { "question": "cozy-stack/port", "vtype": "string", "value": "{{ cozystack_port }}" }
    - { "question": "cozy-stack/admin/address", "vtype": "string", "value": "{{ cozystack_admin_address }}" }
    - { "question": "cozy-stack/admin/port", "vtype": "string", "value": "{{ cozystack_admin_port }}" }

- name: install | install cosy-stack
  apt:
    name: cozy-stack
    state: present
