---
dependency:
  name: galaxy
driver:
  name: lxd
lint:
  name: yamllint
platforms:
  # - name: cozy-instance-xenial
  # groups:
  #   - cozy
  #   - molecule
  #   - all
  # lxd_image: ubuntu/xenial/amd64
  - name: cozy-instance-stretch
    groups:
      - cozy
      - molecule
      - all
    lxd_image: debian/stretch/amd64
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  env:
    ANSIBLE_ROLES_PATH: ${PWD}/roles:${PWD}/roles-dependencies
  playbooks:
    converge: ../../cozy.yml
  inventory:
    links:
      group_vars: ../../../group_vars/
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: report.xml
  lint:
    name: flake8
