---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - net-tools
    - nginx
    - sudo
    - vim-tiny
    - build-essential
    - pkg-config
    - erlang
    - libicu-dev
    - libmozjs185-dev
    - libcurl4-openssl-dev
