---
- name: main | install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - net-tools
    - nginx
    - sudo
    - build-essential
    - pkg-config
    - erlang
    - libicu-dev
    - libmozjs185-dev
    - libcurl4-openssl-dev
