---
- name: main | install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - vim

- name: main | add Cozy key
  shell: >
    curl https://apt.cozy.io/nightly/{{common_cozy_gpg_key }}.gpg | apt-key --keyring /etc/apt/trusted.gpg.d/{{ common_cozy_gpg_key }}.gpg add -
  args:
    creates: "/etc/apt/trusted.gpg.d/{{ common_cozy_gpg_key }}.gpg"
  tags:
    - skip_ansible_lint

- name: main | add Cozy Debian repository
  apt_repository:
    repo: "deb https://apt.cozy.io/nightly/{{ ansible_distribution  | lower }} {{ ansible_distribution_release }} {{ common_cozy_channel }}"
    state: present
