---
- name: main | install base packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - curl
    - apt-transport-https
    - vim

- name: main | define repository url
  set_fact:
    common_cozy_repository_base_url: https://apt.cozy.io/nightly
  when: common_cozy_use_nightly_build

- name: main | add Cozy key
  shell: >
    curl "{{ common_cozy_repository_base_url }}/cozy.gpg" | apt-key --keyring /etc/apt/trusted.gpg.d/cozy.gpg add -
  args:
    creates: "/etc/apt/trusted.gpg.d/cozy.gpg"
  tags:
    - skip_ansible_lint

- name: main | add Cozy Debian repository
  apt_repository:
    repo: "deb {{ common_cozy_repository_base_url }}/{{ ansible_distribution  | lower }} {{ ansible_distribution_release }} {{ common_cozy_channel }}"
    state: present
